# -*- coding: utf-8 -*-
"""debarun_billing_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ue6fJxY_uU068f5dgFOoeephqdTzNsNr

# 🍽️ DeBaRuN's Legendary Billing System
> *Where food is great, bills are real, and the owner cries in GST*
"""

from IPython.display import display, HTML
from datetime import datetime
import random

# ─────────────────────────────────────────
#  ESTABLISHMENT DETAILS
# ─────────────────────────────────────────
ESTABLISHMENT = {
    'name'    : "DeBaRuN's Dhaba & Fine Dining",
    'tagline' : '"Eat like a king, pay like one too."',
    'address' : 'No. 42, Behind the ATM that never works,\nKoramangala 5th Block, Bengaluru - 560095',
    'phone'   : '+91 98765 43210',
    'gstin'   : '29DBRNS9999R1ZX',
    'owner'   : 'DeBaRuN (Yes, the caps are intentional. Don\'t ask.)',
    'fssai'   : '11224403000123',
}

# ─────────────────────────────────────────
#  MENU  (item_no -> (name, price))
# ─────────────────────────────────────────
MENU = {
    '1' : ('Butter Chicken (Extra Butter, Obviously)',           380),
    '2' : ('Paneer Tikka (Paneer sourced from DeBaRuN\'s cow)',   280),
    '3' : ('Garlic Naan (8 cloves min, breath at own risk)',      65),
    '4' : ('Biryani (secret: it\'s just fancy fried rice)',      350),
    '5' : ('Dal Makhani (Simmered since 2019)',                  220),
    '6' : ('Masala Chai (Free if you cry about the bill)',         60),
    '7' : ('Gulab Jamun x2 (DeBaRuN\'s emotional support dessert)',110),
    '8' : ('Chicken 65 (Named after DeBaRuN\'s exam score)',       320),
    '9' : ('Virgin Mojito (DeBaRuN judges you silently)',          180),
    '10': ('DeBaRuN\'s Special Thali (Unknown ingredients, unmatched vibes)', 499),
}

print('╔══════════════════════════════════════════════════════════════╗')
print('║          🍛  DeBaRuN\'s Dhaba & Fine Dining  🍛              ║')
print('║        "Eat like a king, pay like one too."                  ║')
print('╠══════════════════════════════════════════════════════════════╣')
print('║   #   ITEM                                         PRICE     ║')
print('╠══════════════════════════════════════════════════════════════╣')
for k, (name, price) in MENU.items():
    short = name[:46].ljust(47)
    print(f'║  {k.rjust(2)}  {short} ₹{str(price).rjust(4)}  ║')
print('╚══════════════════════════════════════════════════════════════╝')
print('\n  GST @ 18%  (SGST 9% + CGST 9%) applicable on all items.')
print('  DeBaRuN is not responsible for food coma or existential dread.')

# ─────────────────────────────────────────
#  TAKE ORDER
# ─────────────────────────────────────────
print('\n📋  TAKING YOUR ORDER  (type done when finished)')
print('-' * 52)

customer_name = input("Your good name (DeBaRuN will spell it wrong anyway): ").strip() or 'Mysterious Stranger'
table_no      = input('Table number: ').strip() or '??'
covers        = input('Number of guests: ').strip() or '1'

order = []   # list of (name, qty, unit_price)

while True:
    item_no = input('\nEnter item number (or done): ').strip().lower()
    if item_no == 'done':
        if not order:
            print('⚠️  You have not ordered anything. DeBaRuN is concerned.')
            continue
        break
    if item_no not in MENU:
        print('❌  Invalid item. DeBaRuN side-eyes you.')
        continue
    try:
        qty = int(input(f"   Quantity for '{MENU[item_no][0][:35]}': "))
        if qty <= 0:
            print('   Quantity must be > 0. Even DeBaRuN knows that.')
            continue
    except ValueError:
        print('   Numbers only. DeBaRuN does not accept poetry as quantity.')
        continue
    order.append((MENU[item_no][0], qty, MENU[item_no][1]))
    print(f"   ✅  Added {qty}x {MENU[item_no][0][:45]}")

print('\n🎯  Order locked in. DeBaRuN is already judging your choices.')

# ─────────────────────────────────────────
#  TIP SELECTION
# ─────────────────────────────────────────
TIP_OPTIONS = {'1': 10, '2': 15, '3': 20, '4': 0}

print('\n💸  TIP OPTIONS')
print('   1. 10%  — Acceptable. DeBaRuN shrugs.')
print('   2. 15%  — Generous. DeBaRuN nods approvingly.')
print('   3. 20%  — LEGENDARY. DeBaRuN frames your receipt on the wall.')
print('   4.  0%  — No tip. DeBaRuN cries into the dal makhani.')

while True:
    tip_choice = input('\nChoose tip option (1/2/3/4): ').strip()
    if tip_choice in TIP_OPTIONS:
        tip_pct = TIP_OPTIONS[tip_choice]
        break
    print('   Invalid. Even DeBaRuN can count to 4.')

msgs = {20: '🏆 DeBaRuN will name his firstborn after you.',
        15: '🙏 DeBaRuN thanks you from the bottom of his heart.',
        10: '👍 Fair enough. DeBaRuN respects your decision.',
         0: '😢 DeBaRuN is weeping. Happy now?'}
print(f'   {msgs[tip_pct]}')

# ─────────────────────────────────────────
#  CALCULATE TOTALS
# ─────────────────────────────────────────
subtotal    = sum(qty * price for _, qty, price in order)
sgst        = round(subtotal * 0.09, 2)
cgst        = round(subtotal * 0.09, 2)
tip_amt     = round(subtotal * tip_pct / 100, 2)
grand_total = round(subtotal + sgst + cgst + tip_amt, 2)
bill_no     = random.randint(10000, 99999)
now         = datetime.now()

# ─────────────────────────────────────────
#  BUILD HTML BILL
# ─────────────────────────────────────────
rows_html = ''
for name, qty, price in order:
    amt = qty * price
    rows_html += (
        f'<tr>'
        f'<td style="padding:5px 8px;font-size:12px;border-bottom:1px dashed #ddd;">{name}</td>'
        f'<td style="padding:5px 8px;text-align:center;font-size:12px;border-bottom:1px dashed #ddd;">{qty}</td>'
        f'<td style="padding:5px 8px;text-align:right;font-size:12px;border-bottom:1px dashed #ddd;">&#8377;{price}</td>'
        f'<td style="padding:5px 8px;text-align:right;font-size:12px;border-bottom:1px dashed #ddd;">&#8377;{amt}</td>'
        f'</tr>'
    )

tip_label = f'Tip ({tip_pct}%)' if tip_pct > 0 else 'Tip (0%) &mdash; DeBaRuN weeps'
safe_covers = max(int(covers) if covers.isdigit() else 1, 1)

bill_html = f"""
<div style="display:flex;justify-content:center;background:#e8e0d4;padding:40px 20px;">
<div style="
    background:white;
    width:400px;
    padding:32px 36px 36px;
    box-shadow:0 8px 32px rgba(0,0,0,0.22),0 2px 8px rgba(0,0,0,0.10);
    border-radius:2px;
    font-family:'Courier New',Courier,monospace;
    position:relative;
">

  <!-- HEADER -->
  <div style="text-align:center;padding-bottom:16px;border-bottom:2px solid #111;margin-bottom:16px;">
    <div style="font-size:26px;font-weight:900;letter-spacing:3px;">DeBaRuN&#39;s</div>
    <div style="font-size:14px;font-weight:700;letter-spacing:1.5px;margin-top:2px;">DHABA &amp; FINE DINING</div>
    <div style="font-size:10.5px;color:#777;font-style:italic;margin-top:5px;">&ldquo;Eat like a king, pay like one too.&rdquo;</div>
    <div style="margin-top:10px;font-size:10.5px;color:#555;line-height:1.7;">
      No. 42, Behind the ATM that never works,<br>
      Koramangala 5th Block, Bengaluru &mdash; 560095<br>
      &#128222; +91 98765 43210
    </div>
    <div style="margin-top:7px;font-size:9.5px;color:#888;">GSTIN: 29DBRNS9999R1ZX &nbsp;&bull;&nbsp; FSSAI: 11224403000123</div>
    <div style="font-size:9px;color:#bbb;margin-top:2px;">Prop: DeBaRuN &mdash; The caps are intentional. Don&#39;t ask.</div>
  </div>

  <!-- META -->
  <div style="display:flex;justify-content:space-between;font-size:11px;color:#444;margin-bottom:14px;">
    <div style="line-height:1.8;">
      <div><b>Bill No:</b> &nbsp;#{bill_no}</div>
      <div><b>Customer:</b> {customer_name}</div>
      <div><b>Table:</b> {table_no} &nbsp;&bull;&nbsp; <b>Covers:</b> {covers}</div>
    </div>
    <div style="text-align:right;line-height:1.8;">
      <div><b>Date:</b> {now.strftime('%d %b %Y')}</div>
      <div><b>Time:</b> {now.strftime('%I:%M %p')}</div>
      <div style="font-size:9px;color:#bbb;">Cashier: DeBaRuN himself &#128081;</div>
    </div>
  </div>

  <!-- ITEMS -->
  <table style="width:100%;border-collapse:collapse;">
    <thead>
      <tr style="border-top:1px solid #111;border-bottom:1px solid #111;">
        <th style="padding:6px 8px;font-size:11px;text-align:left;">ITEM</th>
        <th style="padding:6px 8px;font-size:11px;text-align:center;">QTY</th>
        <th style="padding:6px 8px;font-size:11px;text-align:right;">RATE</th>
        <th style="padding:6px 8px;font-size:11px;text-align:right;">AMOUNT</th>
      </tr>
    </thead>
    <tbody>{rows_html}</tbody>
  </table>

  <!-- SUBTOTALS -->
  <div style="border-top:1px solid #111;margin-top:8px;padding-top:10px;">
    <table style="width:100%;font-size:12px;">
      <tr>
        <td style="padding:3px 8px;">Subtotal</td>
        <td style="text-align:right;padding:3px 8px;">&#8377;{subtotal:.2f}</td>
      </tr>
      <tr>
        <td style="padding:3px 8px;color:#666;">SGST @ 9%</td>
        <td style="text-align:right;padding:3px 8px;color:#666;">&#8377;{sgst:.2f}</td>
      </tr>
      <tr>
        <td style="padding:3px 8px;color:#666;">CGST @ 9%</td>
        <td style="text-align:right;padding:3px 8px;color:#666;">&#8377;{cgst:.2f}</td>
      </tr>
      <tr>
        <td style="padding:3px 8px;color:#999;font-style:italic;">{tip_label}</td>
        <td style="text-align:right;padding:3px 8px;color:#999;">&#8377;{tip_amt:.2f}</td>
      </tr>
    </table>
  </div>

  <!-- GRAND TOTAL -->
  <div style="border-top:2px solid #111;border-bottom:2px solid #111;margin-top:8px;padding:10px 8px;display:flex;justify-content:space-between;align-items:center;">
    <span style="font-size:14px;font-weight:900;letter-spacing:1px;">GRAND TOTAL</span>
    <span style="font-size:22px;font-weight:900;">&#8377;{grand_total:.2f}</span>
  </div>

  <!-- PER HEAD -->
  <div style="text-align:right;font-size:10px;color:#bbb;margin-top:6px;">
    Per head: &#8377;{grand_total/safe_covers:.2f} &nbsp;(cry together, pay together)
  </div>

  <!-- GST BOX -->
  <div style="margin-top:14px;padding:9px 10px;background:#fafafa;border:1px dashed #ccc;font-size:10px;color:#666;line-height:1.8;">
    <b>GST SUMMARY</b><br>
    Taxable Value: &#8377;{subtotal:.2f} &nbsp;|&nbsp;
    SGST 9%: &#8377;{sgst:.2f} &nbsp;|&nbsp;
    CGST 9%: &#8377;{cgst:.2f}<br>
    Total Tax Collected: &#8377;{sgst+cgst:.2f}
    &nbsp;(DeBaRuN cries paying this to the government)
  </div>

  <!-- FOOTER -->
  <div style="text-align:center;margin-top:20px;font-size:10px;color:#aaa;line-height:1.9;">
    <div style="font-size:13px;letter-spacing:6px;color:#ccc;">&starf; &starf; &starf;</div>
    <div>Thank you for dining with us!</div>
    <div style="font-style:italic;">DeBaRuN made this with love, tears &amp; questionable life choices.</div>
    <div style="margin-top:4px;font-size:9px;">Please visit again. DeBaRuN&#39;s EMI is due next week.</div>
    <div style="margin-top:8px;font-size:9px;color:#ddd;">
      *Computer generated bill. No signature required.<br>
      DeBaRuN will sign it anyway because he loves drama.*
    </div>
  </div>

</div>
</div>
"""

display(HTML(bill_html))